baseurl = "/"
title = "Blog"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
theme = "Hugo-Octopress"


[[menu.main]]
  name = '首页'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = '编程'
  pageRef = '/categories/编程'
  weight = 20
[[menu.main]]
  name = '随笔'
  pageRef = '/categories/随笔'
  weight = 30


[[menu.sidebar]]
  Name = "Tags"
  URL = "/tags/"
  weight = 20
[[menu.sidebar]]
  Name = "Google"
  URL = "https://www.google.com"
  weight = 40
[[menu.sidebar]]
  Name = "Hugo"
  URL = "/categories/hugo/"
  weight = 50

[permalinks]
  post = "/:year-:month-:day-:title/" # change the post URL to look like the old ones


[params]
  # Set to true to enable compact index. Set to false or remove to go back to classic view.
  compactIndex = true
  # This text appears in the site header under website title
  subtitle = "Make it work, make it right, make it fast"

  sidebarMenuEnabled = true
  sidebarHeader = "About me"

  sidebarText = """
  a passionate and curious Software Engineer, Full-Stack Developer with a deep interest in unraveling the complexities of technology.

  Languages: [Java/JavaScript/elixir]
  Frontend: [Vue/HTML/CSS]  
  Backend: [Spring Boot/Phoenix/Mysql]
  Tools & Practices: [Vim/Linux/VSCode]
  """
  navigationNewWindow = false

  sidebarMenuHeader = "other links"

  rss = true  # switch to true to enable RSS icon link

  defaultDescription = ""

  # generate post doc
  tableOfContents = true

  # generate taxonomy list
  generateTaxonomyList = true

  disableGoogleFonts = false

  mainSections = ["posts"]



